"""Initial schema

Revision ID: 0001
Revises: 
Create Date: 2024-04-04 22:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('us_codigo', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('us_nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('us_email', sa.String(length=100), nullable=False),
    sa.Column('us_contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('us_fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('us_fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('us_codigo'),
    sa.UniqueConstraint('us_email'),
    sa.UniqueConstraint('us_nombre_usuario')
    )
    op.create_index(op.f('ix_usuarios_us_email'), 'usuarios', ['us_email'], unique=True)
    op.create_index(op.f('ix_usuarios_us_nombre_usuario'), 'usuarios', ['us_nombre_usuario'], unique=True)
    
    op.create_table('recuerdos',
    sa.Column('re_codigo', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('us_codigo', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('re_titulo', sa.String(length=100), nullable=False),
    sa.Column('re_descripcion', sa.Text(), nullable=True),
    sa.Column('re_fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('re_fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['us_codigo'], ['usuarios.us_codigo'], ),
    sa.PrimaryKeyConstraint('re_codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recuerdos')
    op.drop_index(op.f('ix_usuarios_us_nombre_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_us_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###